[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/igdb/*"
  to = "/.netlify/functions/igdb/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/igdb"
  to = "/.netlify/functions/igdb"
  status = 200
  force = true
